sudo: required
services:
   - docker


before_install:
   -docker build -t johnwildestier/docker-react -f Dockerfile.dev .

script:
  - docker run johnwildestier/docker-react npm run test -- --coverage

#deploy:
  
