sudo: required
services:
   - docker


before_install:
   -docker build -t JohnFrankson1/docker-react -f Dockerfile.dev .

script:
  - docker run JohnFrankson1/docker-react npm run test -- --coverage
